from heap.max_heap import MaxHeap
from heap.min_heap import MinHeap

mh = MaxHeap()
mh.insert(100)
mh.insert(60)
mh.insert(80)
mh.insert(30)
mh.insert(50)
mh.insert(70)
mh.insert(75)
mh.insert(20)
mh.insert(10)
mh.insert(40)
print(mh.heap)
mh.remove_max()
print(mh.heap)
mh.remove_max()
print(mh.heap)

heap = MinHeap()
heap.insert(12)
heap.insert(10)
heap.insert(-10)
heap.insert(100)

print(heap.getMin())
print(heap.removeMin())
print(heap.getMin())
heap.insert(-100)
print(heap.getMin())